config/routes.rb
Rails.application.routes.draw do

  resources :tests, only: [:index, :create, :new, :show, :edit, :update] do
    
    resources :questions, only: [:new, :create]
    
    resources :submissions, only: [:index, :show, :new, :create] do
      resources :answers, only: [:create]
      post 'download' => 'questions#download', as: 'answer_download'
    end

  end

  get 'login' => 'logins#index'
  get 'logout' => 'logins#logout'
  post 'login' => 'logins#create'

end

app/models/answer.rb
class Answer < ActiveRecord::Base

	belongs_to :question
	belongs_to :submission


	def expired?

		if created_at.nil? or question.duration.nil?
			#It means the file was test was never downloaded
			return false
		end

		sec_diff = (Time.now - created_at).to_i.abs
		min_diff = sec_diff / 60
		
		if question.nil?
			return true
		end
			
		min_diff.to_i >= question.duration

	end

	def completed?
		defined?(attachment) and not attachment.nil?
	end

	def expiration_date
		if not created_at.nil? and not question.duration.nil?
			created_at + question.duration * 60
		end
	end

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base

	has_many :tests, through: :submission
	has_many :submissions
	

end

app/models/question.rb
class Question < ActiveRecord::Base

	belongs_to :test



end

app/models/submission.rb
class Submission < ActiveRecord::Base

	belongs_to :applicant
	belongs_to :test

	has_many :answers

	def self.generate_token
		(0...9).map { ('a'..'z').to_a[rand(26)] }.join
	end

	def get_answer_for_question question 
		answers.find{ |a| a.question == question }
	end

end

app/models/test.rb
class Test < ActiveRecord::Base

	has_many :applicants, through: :submission
	has_many :submissions, counter_cache: true
	has_many :questions


end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base

	def self.authenticate(email, password)
		password = Digest::SHA1.hexdigest(password)
		User.where(email: email).where(password: password).take
	end


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	skip_before_filter :require_login


	def create

		@submission = Submission.find_by_token(params[:submission_id])
		@test = @submission.test

		@question = Question.find(params[:question_id])

	
		@answer = @submission.get_answer_for_question @question

		if @answer.nil?
			@answer = Answer.new
			@answer.submission = @submission
			@answer.question = @question
		end

		if not @answer.nil? and not @answer.expired?
			
			uploaded_io = params[:attachment]
			filename = (0...10).map { ('a'..'z').to_a[rand(26)] }.join + '_' + uploaded_io.original_filename.delete(' ')

	  		File.open(Rails.root.join('public', 'attachments', filename), 'wb') do |file|
	    		file.write(uploaded_io.read)
	    	end

	    	@answer.attachment = filename
	    	@answer.save

		end


		redirect_to test_submission_path @test, @submission.token

	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login

  protected
  
  def require_login
  	if not is_logged
  		redirect_to login_path
  	else
  		@user = get_user
  	end
  end

  def is_logged
  	not cookies[:current_user_id].blank?
  end

  def get_user
  	if is_logged
  		User.new
  	end
  end


end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

	skip_before_filter :require_login
	layout "login"

	def index

	end

	def logout
		cookies.delete(:current_user_id)
		redirect_to login_path
	end

	def create

		@user = User.authenticate(params[:email], params[:password])

		if not @user.nil?
			cookies[:current_user_id] = @user.id
			redirect_to tests_path
		else
			flash[:invalid_user] = true
			redirect_to login_path
		end
		
	end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	skip_before_filter :require_login, :only => [:download]


	def new
		@question = Question.new
		@test = Test.find(params[:test_id])
	end

	def create
		
		@question = Question.new(params.require(:question).permit(:title, :description))
		@question.duration = params[:question][:duration].to_i
		@test = Test.find(params[:test_id])

		uploaded_io = params[:question][:attachment]
		filename = (0...10).map { ('a'..'z').to_a[rand(26)] }.join + '_' + uploaded_io.original_filename.delete(' ')
  		
  		File.open(Rails.root.join('public', 'attachments', filename), 'wb') do |file|
    		file.write(uploaded_io.read)
    	end

    	@question.attachment = filename	

		@question.test = @test
		@question.save
		redirect_to test_submissions_path(@test)

	end


	def download

		@question = Question.find(params[:question_id])
		@submission = Submission.find_by_token(params[:submission_id])

		@answer = @submission.get_answer_for_question @question

		if @answer.nil?
			@answer = Answer.new
			@answer.question = @question
			@answer.submission = @submission
		end

		@answer.save

		send_file File.join(Rails.root, 'public', 'attachments', @question.attachment)


	end



end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

	skip_before_filter :require_login, :only => [:show]

	def index
		@submissions = Submission.where(test_id: params[:test_id]).order(updated_at: :desc)
		@test = Test.find(params[:test_id])
	end

	def new
		@submission = Submission.new
		@test = Test.find(params[:test_id])
		@submission.test = @test
		@submission.applicant = Applicant.new
	end

	def show
		@submission = Submission.find_by(token: params[:id])
		@user = get_user
	end

	def create
		
		@submission = Submission.new
		@submission.token = Submission.generate_token
		@applicant = Applicant.new(params[:applicant].permit(:name, :email))
		@applicant.save
		@submission.applicant = @applicant

		@test = Test.find(params[:test_id])
		@submission.test = @test

		@submission.save

		flash[:last_token] = @submission.token
		redirect_to test_submissions_path(@test)
		
	end



end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

	def index
		@tests = Test.order(updated_at: :desc)
	end

	def new
		@test = Test.new
	end

	def show
		@test = Test.find(params[:id])
	end

	def update
		redirect_to tests_path
	end

	def edit
		@test = Test.find(params[:id])
	end

	def create
		@test = Test.new(test_params)
		@test.save
		redirect_to test_submissions_path(@test)
	end


	private
	def test_params
		params.require(:test).permit(:description)
	end



end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SyonTests</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<% if not @user.nil? %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Syon Consultores</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  	  <ul class="nav navbar-nav">
           <li><a href="/tests">Tests</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/logout">Cerrar sesión</a></li>
      </div><!-- /.navbar-collapse -->

    </div><!-- /.container-fluid -->
  </nav>
<% end %>



<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SyonTests</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/logins/index.html.erb
<%= form_tag("/login", method: "post") do %>
	<div class="container" style="margin-top:30px">
		<div class="col-md-4 col-md-offset-4">
			<div class="panel panel-default">
				<div class="panel-heading"><h3 class="panel-title"><strong>Iniciar Sesion</strong></h3></div>
				<div class="panel-body">
					
					<% if flash[:invalid_user] %>
						<div class="form-group has-error text-center">
							<label class="control-label">Usuario/Contraseña inexistente</label>
						</div>
					<% end %>
				
					<div class="form-group">
						<label for="email">Email</label>
						<input type="email" class="form-control" name="email" id="email" required placeholder="Ingrese su email">
					</div>
					<div class="form-group">
						<label for="password">Contraseña</label>
						<input type="password" class="form-control" name="password" required id="password" placeholder="Contraseña">
					</div>
					<br>
					<p class="text-center">
						<button type="submit" class="btn btn-sm btn-default">Iniciar Sesion</button>
					</p>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/questions/new.html.erb
<h1 class="text-center">Nueva pregunta</h1>

<br><br>

<div class="col-sm-4 col-sm-offset-4">
	
	<%= form_for [@test, @question] do |question| %>

		<%= question.label :title, 'Título' %>
		<%= question.text_field :title, class: 'form-control' %>
		<br><br>
			
		
		<%= question.label :description, 'Descripción' %>
		<%= question.text_field :description, class: 'form-control' %>
		<br><br>

		<%= question.label :attachment, 'Adjunto' %>
		<%= question.file_field :attachment, class: 'form-control' %>
		<br><br>
	
		<%= question.label :duration, 'Duración (en minutos)' %>
		<%= question.number_field :duration, class: 'form-control' %>
		<br><br>

		<p class="text-center">

		<a href="<%= test_submissions_path(@test) %>" class="btn btn-primary">
				<i class="fa fa-arrow-left icon-button"></i> Volver</a> 
			<%= question.submit 'Guardar pregunta', class: 'btn btn-success' %>
		</p>

	<% end %>

</div>

app/views/submissions/index.html.erb
<h1 class="text-center">Entregas de <%= @test.description %></h1>

<% if flash[:last_token] %>
	<br>
	
	<div class="alert alert-success text-center">Link generado 
		<strong>
			<a href="http://localhost:3000<%= test_submission_path(@test.id, flash[:last_token]) %>">http://localhost:3000<%= test_submission_path(@test.id, flash[:last_token]) %></a>
		</strong>
	</div>

<% end %>

<br>


<a class="btn btn-primary" href="<%= tests_path %>"><i class="fa fa-arrow-left icon-button"></i> Volver</a>

<a class="btn btn-success" href="<%= new_test_submission_path %>"><i class="fa fa-plus icon-button"></i> Crear nueva entrega</a>

<a class="btn btn-default" href="<%= new_test_question_path(@test) %>"><i class="fa fa-plus icon-button"></i>  Agregar pregunta</a>


<br /><br /><br />

<table class="table table-hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>Nombre</th>
			<th>Email</th>
			<th class="text-center">Acción</th>
		</tr>
	</thead>
	<tbody>
		<% @submissions.each do |submission| %>
			<tr>
				<td><%= submission.id %></td>
				<td><%= submission.applicant.name %></td>
				<td><%= submission.applicant.email %></td>
				<td class="text-center">
					<a class='btn btn-default' href="<%= test_submission_path(@test, submission.token) %>"><i class="fa fa-check icon-button"></i> Ver</a>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/submissions/new.html.erb
<h1 class="text-center">Crear un nuevo submission para la persona: </h1>

<br><br>

<div class="col-md-4 col-md-offset-4">

	<%= form_for [@test, @submission] do |f| %>

		<%= fields_for :applicant do |f_applicant| %>
		
			<p>
				<%= f_applicant.label :name, 'Nombre' %>
				<%= f_applicant.text_field :name, class: 'form-control' %>
			</p>
			
			<br>

			<p>
				<%= f_applicant.label :email %>
				<%= f_applicant.text_field :email, class: 'form-control' %>
			</p>

		<% end %>
		
		<br><br>

		<p class="text-center">
			<a href="<%= test_submissions_path(@test) %>" class="btn btn-primary">
				<i class="fa fa-arrow-left icon-button"></i> Volver
			</a> 
			<%= f.submit "Generar link!", class: 'btn btn-success' %>
		</p>

	<% end %>

</div>

app/views/submissions/show.html.erb
<% unless @user.nil? %>
	<h1 class="text-center">
			<a href="<%= test_submissions_path(@submission.test) %>" class="btn btn-default" style="margin-bottom: 5px; margin-right: 30px;">
				<i class="fa fa-arrow-left icon-button"></i> Volver</a> 
		Entrega de: <%= @submission.applicant.name %>
	</h1>
<% end %>

<br><br>

<h3>Preguntas:</h3>
<hr>

<% @submission.test.questions.each do |question| %>
	
	<div class="row">
		
		<div class="col-md-10 col-md-offset-1">
			
			<h4><strong><%= question.title %></strong></h4>
			
			<br>

			<p><%= question.description %></p>
			
			<p><strong>Duración: </strong><%= question.duration %> minutos</p>
			<br>
			
			<div class="col-md-6 text-center">
				
				<i class="fa fa-file-text-o" style="font-size: 10em"></i>

				<br><br>

				<%= form_tag(test_submission_answer_download_path(question.test, @submission.token), method: "post") do %>

					<%= hidden_field_tag 'question_id', question.id %>
					<button class="btn btn-success" type="submit"><i class="fa fa-download"></i> Descargar</button>

				<% end %>

			</div>


			<div class="col-md-6 text-center" style="margin-top: 60px;">
				
				<% answer = @submission.get_answer_for_question question
				 if answer.nil? 
					answer = Answer.new
				end %>

				<% if not answer.expiration_date.nil? and not answer.expired? %>
					<p>Tiene tiempo para subir su respuesta hasta <%= answer.expiration_date.strftime("%d/%m/%Y %H:%M") %>  </p>
				<% end %>

				<% if answer.completed?  %>

					<p>Subió su respuesta el día <%= answer.updated_at.strftime("%d/%m/%Y %H:%M") %> 
						<% if not @user.nil? %>
							<a href="/attachments/<%= answer.attachment %>" target="_blank">Descargar</a>
						<% end %>
					</p>

				<% end %>

				<% if not answer.expired? %>
					

					<%= form_tag(test_submission_answers_path(question.test, @submission.token), method: "post", multipart: true) do %>
						
						<%= hidden_field_tag 'question_id', question.id %>

						<fieldset>
					 		<%= file_field_tag :attachment, class: 'form-control' %>
						</fieldset>	
						<br />		
						<fieldset>
					 		<button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o"></i> Guardar respuesta</button>
						</fieldset>
						
					<% end %>
					

				<% else %>
					
					<% if not answer.completed? and answer.expired? %>
					
						<label style="color: red"><strong>El tiempo para subir la respuesta expiró</strong></label>

					<% end %>
				
				<% end %>

			
			</div>

		</div>

	</div>
	
	<% unless question == @submission.test.questions.last %>
		<hr>
	<% end %>


<% end %>


<br><br>